name: Deploy to HostGator

on:
  push:
    branches:
      - main  # Use uma lista para especificar o branch
  pull_request:
    branches:
      - main  # Use uma lista para especificar o branch

jobs:
  web-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Atualizado para a versão mais recente

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3  # Atualizado para a versão mais recente
        with:
          node-version: '20'  # Atualizado para a versão Node.js 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        run: npm run deploy

    env:
      FTP_HOST: ${{ secrets.FTP_HOST }}
      FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
      FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      FTP_PORT: ${{ secrets.FTP_PORT }}
